{ config, pkgs, options, ... }: {
  imports = [
    ./cachix/nix-community.nix
    ./nix.nix
    ./private/filesystems-remote.nix
    ./private/i18n.nix
    ./private/time.nix
    ./private/users.nix
    ./security.nix
    ./services/acpid.nix
    ./services/atd.nix
    ./services/logind.nix
    ./services/nix-gc.nix
    ./services/nix-serve.nix
    ./services/ssh.nix
    ./system.nix
    ./desa/packages/bash.nix
    ./desa/packages/devops.nix
    ./desa/packages/editors.nix
    ./desa/packages/nix.nix
    ./desa/packages/version-control.nix
    ./desa/private/boot-common.nix
    ./desa/private/boot.nix
    ./desa/private/console.nix
    ./desa/private/filesystems.nix
    ./desa/private/hardware.nix
    ./desa/private/power.nix
    ./desa/private/networking.nix
    ./desa/private/nix.nix
    ./desa/private/services/docker.nix
    ./desa/private/services/kubernetes.nix
    ./desa/programs.nix
    ./desa/services/libvirtd.nix
  ];
}
