{ config, pkgs, ... }:

{
  # Enable the X11 windowing system.
  services.xserver = {
    videoDrivers = [ "nvidia" ];
#    videoDrivers = [ "amdgpu" "nvidia" ]; # doesn't work
    exportConfiguration = true;
#    xrandrHeads = [
#      { output = "HDMI-0"; } # lg-hd
##      { output = "eDP"; primary = true; } # laptop
#      { output = "DP-0"; monitorConfig = "Option \"Rotate\" \"left\""; } # samsung-vertical
#      { output = "DP-2"; } # samsung-4k
#    ];

     config = pkgs.lib.mkAfter ''

# nvidia-settings: X configuration file generated by nvidia-settings
# nvidia-settings:  version 535.113.01

# Additional "InputClass" sections
# For each supported driver, add a "Device" and "Screen"
# section.

#Section "ServerLayout"

  # Reference the Screen sections for each driver.  This will
  # cause the X server to try each in turn.
#    Identifier     "Layout[all]"
#    Screen      0  "Screen0" 0 0
#    Inactive       "Device-amdgpu[0]"
#    InputDevice    "Keyboard0" "CoreKeyboard"
#    InputDevice    "Mouse0" "CorePointer"
#    Option         "Xinerama" "0"
#EndSection

Section "ServerLayout"

#  Reference the Screen sections for each driver.  This will
#  cause the X server to try each in turn.
#  Screen "Screen-nvidia-HDMI-0" RightOf "Screen-amdgpu-eDP"
    Identifier     "Layout"
    Screen         "Screen-nvidia-DP-2" 0 0
    Screen         "Screen-nvidia-DP-0" 0 0
    Screen         "Screen-nvidia-HDMI-0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
EndSection

Section "Files"
    ModulePath      "${config.boot.kernelPackages.nvidia_x11}/lib"
#    ModulePath      "${pkgs.linuxPackages.nvidiaPackages.latest}/lib"
#    ModulePath      "${pkgs.xorg.xf86videoamdgpu}/lib/xorg/modules/drivers"
    ModulePath      "${pkgs.xorg.xorgserver}/lib/xorg/modules"
    ModulePath      "${pkgs.xorg.xorgserver}/lib/xorg/modules/drivers"
    ModulePath      "${pkgs.xorg.xorgserver}/lib/xorg/modules/extensions"
    ModulePath      "${pkgs.xorg.xorgserver}/lib/xorg/modules/input"
    ModulePath      "${pkgs.xorg.xf86inputlibinput}/lib/xorg/modules/input"
    ModulePath      "${pkgs.xorg.xf86inputevdev}/lib/xorg/modules/input"
#    ModulePath      "/nix/store/nrclw8lg1mmfirj2a3zsd4x7aw2rkm57-xf86-input-wacom-1.2.0/lib/xorg/modules/input"
    FontPath        "${pkgs.dosemu_fonts}/share/fonts/X11/misc/dosemu"
    FontPath        "${pkgs.gohufont}/share/fonts/misc"
    FontPath        "${pkgs.proggyfonts}/share/fonts/misc"
    FontPath        "${pkgs.terminus_font}/share/fonts/terminus"
    FontPath        "${pkgs.tewi-font}/share/fonts/misc"
    FontPath        "${pkgs.ucs-fonts}/share/fonts/misc"
    FontPath        "${pkgs.unifont}/share/fonts"
EndSection

Section "Module"
EndSection

Section "ServerFlags"
    Option         "AllowMouseOpenFail" "on"
    Option         "DontZap" "on"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/input/mice"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputClass"
    Identifier         "libinput mouse configuration"
    MatchIsPointer     "on"
    MatchDriver        "libinput"
    Option         "AccelProfile" "adaptive"
    Option         "LeftHanded" "off"
    Option         "MiddleEmulation" "on"
    Option         "NaturalScrolling" "off"
    Option         "ScrollMethod" "twofinger"
    Option         "HorizontalScrolling" "on"
    Option         "SendEventsMode" "enabled"
    Option         "Tapping" "on"
    Option         "TappingDragLock" "on"
    Option         "DisableWhileTyping" "off"
EndSection

Section "InputClass"
    Identifier         "libinput touchpad configuration"
    MatchIsTouchpad    "on"
    MatchDriver        "libinput"
    Option         "AccelProfile" "adaptive"
    Option         "LeftHanded" "off"
    Option         "MiddleEmulation" "on"
    Option         "NaturalScrolling" "off"
    Option         "ScrollMethod" "twofinger"
    Option         "HorizontalScrolling" "on"
    Option         "SendEventsMode" "enabled"
    Option         "Tapping" "off"
    Option         "TappingDragLock" "on"
    Option         "DisableWhileTyping" "off"
EndSection

Section "Monitor"
    Identifier     "Monitor[0]"
EndSection

Section "Monitor"
    Identifier     "DP-2"
    Option         "Primary" "true"
    Option         "Rotate" "inverted"
    Option         "PreferredMode" "3840x2160"
    Option         "Enable" "true"
EndSection

Section "Monitor"
    Identifier     "DP-0"
    Option         "RightOf" "DP-2"
    Option         "Rotate" "left"
    Option         "PreferredMode" "1680x1050"
    Option         "Position" "3840 0"
    Option         "Enable" "true"
EndSection

Section "Monitor"
    Identifier     "HDMI-0"
    Option         "RightOf" "DP-0"
    Option         "PreferredMode" "1920x1080"
    Option         "Enable" "true"
    Option         "Position" "4890 434"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "DELL S3422DWG"
    HorizSync       29.0 - 200.0
    VertRefresh     48.0 - 120.0
EndSection

#Section "Device"
#    Identifier     "Device-amdgpu[0]"
#    Driver         "amdgpu"
#    BusID          "PCI:6:0:0"
#EndSection

#Section "Device"
#    Identifier     "Device-nvidia[0]"
#    Driver         "nvidia"
#    BusID          "PCI:1:0:0"
#EndSection

Section "Device"
    Identifier     "Device-nvidia"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce RTX 3070 mobile"
    Option         "Monitor-HDMI-0" "HDMI-0"
    Option         "Monitor-DP-0" "DP-0"
    Option         "Monitor-DP-2" "DP-2"
    Option         "UseDisplayDevice" "HDMI-1"
    Option         "RenderAccel" "true"
    BusID          "PCI:1:0:0"
    Screen          0
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "NVIDIA GeForce RTX 3070 Laptop GPU"
EndSection

#Section "Screen"
#    Identifier     "Screen-nvidia[0]"
#    Device         "Device-nvidia[0]"
#    Monitor        "Monitor[0]"
#    Option         "AllowEmptyInitialConfiguration"
#EndSection

Section "Screen"
    Identifier     "Screen-nvidia-HDMI-0"
    Device         "Device-nvidia"
    Monitor        "HDMI-0"
    Option         "AllowEmptyInitialConfiguration"
EndSection

Section "Screen"
    Identifier     "Screen-nvidia-DP-0"
    Device         "Device-nvidia"
    Monitor        "DP-0"
    Option         "AllowEmptyInitialConfiguration"
EndSection

Section "Screen"
    Identifier     "Screen-nvidia-DP-2"
    Device         "Device-nvidia"
    Monitor        "DP-2"
    Option         "AllowEmptyInitialConfiguration"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-0"
#    Option         "metamodes" "DP-2: nvidia-auto-select +1050+120 {rotation=inverted}, HDMI-0: nvidia-auto-select +1050+120, DP-0: nvidia-auto-select +0+0 {rotation=left}"
    Option         "metamodes" "DP-2: nvidia-auto-select +0+0 {rotation=invert}, HDMI-0: nvidia-auto-select +4890+481, DP-0: nvidia-auto-select +3840+361 {rotation=left}"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "Off"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

'';
    displayManager = {
      sessionCommands =  ''
#         su - chous 'xmonad --recompile' || echo "nevermind"
#         ls -lthlia ~/.Xauthority ~/.xmonad >> /tmp/session.log
#         chown chous:users /home/chous/.Xauthority
#         rm -f /home/chous/.xmonad/xmonad-x86_64-linux
         xmodmap -e 'add mod3 = Multi_key'
      '';
      lightdm = { enable = true; };
    };
  };
}
