[Interface]
Address = 10.252.1.1/32
PrivateKey = GDNUXBsfoqQArflxJFdGiXnoGgwQN4R9YFcK601+f0s=
MTU = 1316

[Peer]
PublicKey = iarOJ7RLo8Jfnbek1iK8/5h/i0iaRXUrLkQg756ZISc=
PresharedKey = deYF36LBZQaFuAhIvgLXAcsptFr6qpz6TjrvCQw9Z3U=
AllowedIPs = 10.252.1.0/24,172.30.1.0/24
Endpoint = 49.13.108.105:51820
PersistentKeepalive = 15
