# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }: {
  imports = [ # <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  hardware = {
    cpu.amd.updateMicrocode = true;
    enableAllFirmware = true;
    graphics = {
      enable = true;
      enable32Bit = true;
    };
    nvidia-container-toolkit = { enable = true; };
    nvidia = { datacenter = { enable = false; }; };
  };

  nix.settings.max-jobs = lib.mkDefault 16;
}
